In [62]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB


In [64]:
df=pd.read_csv("heart.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Sex             918 non-null    object 
 2   ChestPainType   918 non-null    object 
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      918 non-null    object 
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    object 
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object 
 11  HeartDisease    918 non-null    int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB


In [5]:
df.head(6)

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   
5   39   M           NAP        120          339          0     Normal    170   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0  
5              N      0.0       Up             0

In [6]:
df.tail(6)

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
912   57   F           ASY        140          241          0     Normal   
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
912    123              Y      0.2     Flat             1  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0

In [7]:
df.describe()

Age   RestingBP  Cholesterol   FastingBS       MaxHR  \
count  918.000000  918.000000   918.000000  918.000000  918.000000   
mean    53.510893  132.396514   198.799564    0.233115  136.809368   
std      9.432617   18.514154   109.384145    0.423046   25.460334   
min     28.000000    0.000000     0.000000    0.000000   60.000000   
25%     47.000000  120.000000   173.250000    0.000000  120.000000   
50%     54.000000  130.000000   223.000000    0.000000  138.000000   
75%     60.000000  140.000000   267.000000    0.000000  156.000000   
max     77.000000  200.000000   603.000000    1.000000  202.000000   

          Oldpeak  HeartDisease  
count  918.000000    918.000000  
mean     0.887364      0.553377  
std      1.066570      0.497414  
min     -2.600000      0.000000  
25%      0.000000      0.000000  
50%      0.600000      1.000000  
75%      1.500000      1.000000  
max      6.200000      1.000000

In [8]:
df.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [9]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Sex']=le.fit_transform(df['Sex'])
df['ChestPainType']=le.fit_transform(df['ChestPainType'])
df['RestingECG']=le.fit_transform(df['RestingECG'])
df['ExerciseAngina']=le.fit_transform(df['ExerciseAngina'])
df['ST_Slope']=le.fit_transform(df['ST_Slope'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Sex             918 non-null    int64  
 2   ChestPainType   918 non-null    int64  
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      918 non-null    int64  
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    int64  
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    int64  
 11  HeartDisease    918 non-null    int64  
dtypes: float64(1), int64(11)
memory usage: 86.2 KB


In [40]:
x=df.drop(['HeartDisease'],axis=1)
y=df['HeartDisease']
x

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0     40    1              1        140          289          0           1   
1     49    0              2        160          180          0           1   
2     37    1              1        130          283          0           2   
3     48    0              0        138          214          0           1   
4     54    1              2        150          195          0           1   
..   ...  ...            ...        ...          ...        ...         ...   
913   45    1              3        110          264          0           1   
914   68    1              0        144          193          1           1   
915   57    1              0        130          131          0           1   
916   57    0              1        130          236          0           0   
917   38    1              2        138          175          0           1   

     MaxHR  ExerciseAngina  Oldpeak  ST_Slope  
0      172               0      0.0         2  
1      156               0      1.0         1  
2       98               0      0.0         2  
3      108               1      1.5         1  
4      122               0      0.0         2  
..     ...             ...      ...       ...  
913    132               0      1.2         1  
914    141               0      3.4         1  
915    115               1      1.2         1  
916    174               0      0.0         1  
917    173               0      0.0         2  

[918 rows x 11 columns]

In [41]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)
x

array([[-1.4331398 ,  0.51595242,  0.22903206, ..., -0.8235563 ,
        -0.83243239,  1.05211381],
       [-0.47848359, -1.93816322,  1.27505906, ..., -0.8235563 ,
         0.10566353, -0.59607813],
       [-1.75135854,  0.51595242,  0.22903206, ..., -0.8235563 ,
        -0.83243239,  1.05211381],
       ...,
       [ 0.37009972,  0.51595242, -0.81699495, ...,  1.21424608,
         0.29328271, -0.59607813],
       [ 0.37009972, -1.93816322,  0.22903206, ..., -0.8235563 ,
        -0.83243239, -0.59607813],
       [-1.64528563,  0.51595242,  1.27505906, ..., -0.8235563 ,
        -0.83243239,  1.05211381]], shape=(918, 11))

In [42]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=40)
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)
a_pred=model.predict(x_test)
print(a_pred)

[1 0 1 1 0 0 1 0 1 1 0 0 1 1 1 1 0 0 0 1 1 1 0 0 0 1 1 0 0 0 1 0 1 0 1 1 0
 0 1 1 0 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 0 1 1
 1 1 1 0 1 1 1 1 1 1 0 0 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 0 1 0 0 1 1 1 0 1 0
 0 1 1 0 0 0 0 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 0 0 0 1 0 0 1 0 1 1 0 0 1 0 0
 1 1 0 1 0 1 1 1 0 0 1 0 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 0 1 1 0]


In [43]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
a1=accuracy_score(y_test,a_pred)
print(a1)
a2=confusion_matrix(y_test,a_pred)
print(a2)
a3=classification_report(y_test,a_pred)
print(a3)


0.8858695652173914
[[ 63  12]
 [  9 100]]
              precision    recall  f1-score   support

           0       0.88      0.84      0.86        75
           1       0.89      0.92      0.90       109

    accuracy                           0.89       184
   macro avg       0.88      0.88      0.88       184
weighted avg       0.89      0.89      0.89       184



In [44]:
model=LogisticRegression()
model.fit(x_test,y_test)
b_pred=model.predict(x_test)
print(b_pred)

[1 0 1 1 0 0 1 0 1 1 0 0 1 1 1 1 0 0 0 1 0 1 0 0 0 1 1 0 0 0 1 0 1 0 1 1 0
 0 1 1 0 1 1 1 1 1 1 1 0 0 1 0 0 0 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 0 1 1
 1 1 1 0 1 1 1 1 1 1 0 0 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 0 1 0
 0 1 1 0 0 0 0 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 0 0 0 1 0 0 1 0 1 1 0 0 1 0 0
 1 1 0 1 0 1 1 1 0 0 1 0 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 0 1 1 0]


In [45]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
a4=accuracy_score(y_test,b_pred)
print(a4)
a5=confusion_matrix(y_test,b_pred)
print(a5)
a6=classification_report(y_test,b_pred)
print(a6)

0.9021739130434783
[[ 64  11]
 [  7 102]]
              precision    recall  f1-score   support

           0       0.90      0.85      0.88        75
           1       0.90      0.94      0.92       109

    accuracy                           0.90       184
   macro avg       0.90      0.89      0.90       184
weighted avg       0.90      0.90      0.90       184



In [46]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=40)
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(x_train,y_train)
c_pred=model.predict(x_test)
print(c_pred)

[1 0 1 1 0 0 1 0 1 1 0 0 1 1 1 1 0 0 0 1 1 1 0 1 0 1 1 0 0 0 1 0 0 0 1 1 0
 0 1 1 0 1 1 1 1 1 1 0 0 0 1 0 0 0 1 1 1 1 0 1 1 1 0 1 0 0 0 1 1 1 1 0 1 1
 1 1 0 0 1 1 1 1 1 1 0 0 1 1 1 1 0 0 0 1 0 1 1 1 1 1 1 0 1 0 1 0 1 1 0 1 0
 0 1 1 0 0 0 0 1 1 1 0 0 1 1 1 0 1 1 0 0 1 1 0 0 0 1 0 0 1 0 1 1 0 0 1 0 0
 1 1 0 1 0 1 1 1 0 0 1 0 1 1 0 1 1 1 0 1 0 1 1 1 0 1 1 0 1 1 1 1 0 1 1 0]


In [47]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
b1=accuracy_score(y_test,c_pred)
print(b1)
b2=confusion_matrix(y_test,c_pred)
print(b2)
b3=classification_report(y_test,c_pred)
print(b3)

0.8695652173913043
[[64 11]
 [13 96]]
              precision    recall  f1-score   support

           0       0.83      0.85      0.84        75
           1       0.90      0.88      0.89       109

    accuracy                           0.87       184
   macro avg       0.86      0.87      0.87       184
weighted avg       0.87      0.87      0.87       184



In [48]:
model=RandomForestClassifier()
model.fit(x_test,y_test)
d_pred=model.predict(x_test)
print(d_pred)

[1 0 0 1 0 0 1 0 1 1 0 0 1 0 1 1 0 1 0 1 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0
 0 1 1 0 1 0 1 1 1 1 1 0 0 1 0 0 0 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 0 1 1
 1 0 1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 1 0 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1
 0 1 1 0 1 1 0 0 1 1 1 0 1 1 1 0 1 1 0 0 1 1 0 0 0 1 1 0 1 0 1 1 0 0 1 0 0
 0 1 0 1 0 1 1 1 0 0 1 0 1 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 1 1 1 1 0 0 1 0]


In [49]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
b4=accuracy_score(y_test,d_pred)
print(b4)
b5=confusion_matrix(y_test,d_pred)
print(b5)
b6=classification_report(y_test,d_pred)
print(b6)

1.0
[[ 75   0]
 [  0 109]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        75
           1       1.00      1.00      1.00       109

    accuracy                           1.00       184
   macro avg       1.00      1.00      1.00       184
weighted avg       1.00      1.00      1.00       184



In [50]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=40)
from sklearn.tree import DecisionTreeClassifier 
model=DecisionTreeClassifier()
model.fit(x_train,y_train)
e_pred=model.predict(x_test)
print(e_pred)

[1 0 0 1 0 0 1 0 1 1 0 0 0 1 1 1 0 0 0 1 0 1 0 1 0 1 1 0 0 0 1 0 1 0 1 1 0
 0 1 1 0 1 1 1 1 1 1 1 0 0 1 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 0 1 1 1 0 0 1 0
 1 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 1 0 1 1 1 1 1 1 0 1 0 1 0 1 1 0 1 1
 0 1 0 0 0 0 1 1 1 1 0 0 1 1 1 0 1 0 0 0 1 1 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0
 1 1 0 1 0 1 1 1 0 0 1 0 1 1 1 0 1 0 0 1 0 1 1 1 0 1 1 0 1 1 1 1 0 1 1 0]


In [51]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
c1=accuracy_score(y_test,e_pred)
print(c1)
c2=confusion_matrix(y_test,e_pred)
print(c2)
c3=classification_report(y_test,e_pred)
print(c3)

0.8043478260869565
[[62 13]
 [23 86]]
              precision    recall  f1-score   support

           0       0.73      0.83      0.78        75
           1       0.87      0.79      0.83       109

    accuracy                           0.80       184
   macro avg       0.80      0.81      0.80       184
weighted avg       0.81      0.80      0.81       184



In [52]:
model=DecisionTreeClassifier()
model.fit(x_test,y_test)
f_pred=model.predict(x_test)
print(f_pred)

[1 0 0 1 0 0 1 0 1 1 0 0 1 0 1 1 0 1 0 1 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0
 0 1 1 0 1 0 1 1 1 1 1 0 0 1 0 0 0 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 0 1 1
 1 0 1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 1 0 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1
 0 1 1 0 1 1 0 0 1 1 1 0 1 1 1 0 1 1 0 0 1 1 0 0 0 1 1 0 1 0 1 1 0 0 1 0 0
 0 1 0 1 0 1 1 1 0 0 1 0 1 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 1 1 1 1 0 0 1 0]


In [53]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
c4=accuracy_score(y_test,f_pred)
print(c4)
c5=confusion_matrix(y_test,f_pred)
print(c5)
c6=classification_report(y_test,f_pred)
print(c6)

1.0
[[ 75   0]
 [  0 109]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        75
           1       1.00      1.00      1.00       109

    accuracy                           1.00       184
   macro avg       1.00      1.00      1.00       184
weighted avg       1.00      1.00      1.00       184



In [54]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=40)
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)
g_pred=model.predict(x_test)
print(g_pred)

[1 0 1 1 0 0 1 0 1 1 0 0 1 1 1 1 0 0 0 1 1 1 0 1 0 1 1 0 0 0 1 0 1 0 1 1 0
 0 1 1 0 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 0 1 1
 1 1 1 0 1 1 0 1 1 1 0 0 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 0 1 1
 0 1 1 0 0 0 0 1 1 1 0 0 1 1 1 0 1 1 0 0 1 1 0 0 0 1 1 0 1 0 1 1 0 0 1 0 0
 1 1 0 1 0 1 1 1 0 0 1 0 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 0 1 1 0]


In [55]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
d1=accuracy_score(y_test,g_pred)
print(d1)
d2=confusion_matrix(y_test,g_pred)
print(d2)
d3=classification_report(y_test,g_pred)
print(d3)

0.8858695652173914
[[ 62  13]
 [  8 101]]
              precision    recall  f1-score   support

           0       0.89      0.83      0.86        75
           1       0.89      0.93      0.91       109

    accuracy                           0.89       184
   macro avg       0.89      0.88      0.88       184
weighted avg       0.89      0.89      0.89       184



In [56]:
model=SVC()
model.fit(x_test,y_test)
h_pred=model.predict(x_test)
print(h_pred)

[1 0 0 1 0 0 1 0 1 1 0 0 1 1 1 1 0 0 0 1 1 1 0 0 0 1 1 0 0 0 1 0 1 0 1 1 0
 0 1 1 0 1 1 1 1 1 1 1 0 0 1 0 0 0 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 0 1 1
 1 1 1 0 1 1 1 1 1 1 0 0 1 1 1 1 0 0 0 1 0 1 1 1 1 1 1 0 1 0 1 1 1 1 0 1 1
 0 1 1 0 0 0 0 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 0 0 0 1 1 0 1 0 1 1 0 0 1 0 0
 0 1 0 1 0 1 1 1 0 0 1 0 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 0 1 1 0]


In [57]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
d4=accuracy_score(y_test,h_pred)
print(d4)
d5=confusion_matrix(y_test,h_pred)
print(d5)
d6=classification_report(y_test,h_pred)
print(d6)

0.9239130434782609
[[ 66   9]
 [  5 104]]
              precision    recall  f1-score   support

           0       0.93      0.88      0.90        75
           1       0.92      0.95      0.94       109

    accuracy                           0.92       184
   macro avg       0.92      0.92      0.92       184
weighted avg       0.92      0.92      0.92       184



In [58]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=40)
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(x_train,y_train)
i_pred=model.predict(x_test)
print(i_pred)

[1 0 1 1 0 0 1 0 1 1 0 0 1 0 1 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0
 0 1 1 0 1 1 1 1 1 1 1 0 0 1 0 0 0 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 0 1 1
 1 1 0 0 1 1 0 1 0 1 0 0 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 0 1 0 0 1 1 1 0 1 0
 0 1 1 0 0 0 0 0 1 1 1 0 1 1 1 0 1 1 0 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 1 0 0
 1 1 0 1 0 1 1 1 0 0 1 0 1 1 1 1 1 1 0 1 0 1 1 1 0 1 1 0 1 1 1 1 0 1 1 1]


In [59]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
e1=accuracy_score(y_test,i_pred)
print(e1)
e2=confusion_matrix(y_test,i_pred)
print(e2)
e3=classification_report(y_test,i_pred)
print(e3)

0.8641304347826086
[[65 10]
 [15 94]]
              precision    recall  f1-score   support

           0       0.81      0.87      0.84        75
           1       0.90      0.86      0.88       109

    accuracy                           0.86       184
   macro avg       0.86      0.86      0.86       184
weighted avg       0.87      0.86      0.86       184



In [60]:
model=GaussianNB()
model.fit(x_test,y_test)
j_pred=model.predict(x_test)
print(j_pred)

[1 0 1 1 0 0 1 0 1 1 0 0 1 0 1 0 0 0 0 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0
 0 1 1 0 1 1 1 1 1 1 1 0 0 1 0 0 0 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 0 1 1
 1 1 1 0 1 1 0 1 0 1 0 0 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 0 1 0
 0 1 1 0 0 0 0 0 1 1 1 0 1 1 1 0 1 1 0 0 1 1 0 0 0 1 0 0 1 0 1 1 0 0 1 0 0
 1 1 0 1 0 1 1 1 0 0 1 0 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 0 1 1 0]


In [61]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
e4=accuracy_score(y_test,j_pred)
print(e4)
e5=confusion_matrix(y_test,j_pred)
print(e5)
e6=classification_report(y_test,j_pred)
print(e6)

0.8913043478260869
[[66  9]
 [11 98]]
              precision    recall  f1-score   support

           0       0.86      0.88      0.87        75
           1       0.92      0.90      0.91       109

    accuracy                           0.89       184
   macro avg       0.89      0.89      0.89       184
weighted avg       0.89      0.89      0.89       184

